
#  Application

spring.application.name=ud-marketplace-auth
server.port=8080


#  Database — MySQL

spring.datasource.url=jdbc:mysql://localhost:3306/marketplace?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=MySQL

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false


#  JWT

app.jwt.secret=UdMarketplace_SuperSecretKey_2024_MustBe32CharsOrMore!
app.jwt.expiration-ms=86400000


#  2FA y seguridad

app.auth.max-intentos-fallidos=5
app.auth.minutos-bloqueo=30
app.auth.minutos-expiry-2fa=10
app.auth.minutos-expiry-token-recuperacion=60


#  Python backend (email / geolocalización)
# Cambiar al URL real del servicio Python

app.python.base-url=http://localhost:5000 



#  Subida de archivos

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB


#  Logging

logging.level.com.udmarketplace=DEBUG
logging.level.org.springframework.security=WARN
